SET(NGLIB_FPIC_SRCS nglib/nglib.cpp
	libsrc/geom2d/genmesh2d.cpp
	libsrc/geom2d/geom2dmesh.cpp
	libsrc/meshing/global.cpp
	libsrc/meshing/hprefinement.cpp
	libsrc/meshing/meshclass.cpp
	libsrc/meshing/meshfunc.cpp
	libsrc/stlgeom/meshstlsurface.cpp
	libsrc/meshing/meshtype.cpp
	libsrc/geom2d/splinegeometry.cpp
	libsrc/stlgeom/stlgeom.cpp
	libsrc/stlgeom/stltool.cpp
	libsrc/stlgeom/stltopology.cpp
	libsrc/meshing/meshfunc2d.cpp
	libsrc/meshing/meshing2.cpp
	libsrc/meshing/meshing3.cpp
	libsrc/meshing/meshtool.cpp
	libsrc/meshing/msghandler.cpp
	libsrc/general/mystring.cpp
	libsrc/general/ngexception.cpp
	libsrc/general/profiler.cpp
	libsrc/meshing/smoothing2.cpp
	libsrc/meshing/smoothing3.cpp
	libsrc/stlgeom/stlgeomchart.cpp
	libsrc/stlgeom/stlgeommesh.cpp
	libsrc/stlgeom/stlline.cpp
	libsrc/general/symbolta.cpp
	libsrc/general/table.cpp
	libsrc/stlgeom/stltopology.cpp
	libsrc/meshing/topology.cpp
	libsrc/gprim/adtree.cpp
	libsrc/meshing/bisect.cpp
	libsrc/general/bitarray.cpp
	libsrc/meshing/clusters.cpp
	libsrc/csg/csgparser.cpp
	libsrc/meshing/curvedelems.cpp
	libsrc/meshing/delaunay.cpp
	libsrc/linalg/densemat.cpp
	libsrc/general/dynamicmem.cpp
	libsrc/general/flags.cpp
	libsrc/gprim/geom2d.cpp
	libsrc/gprim/geom3d.cpp
	libsrc/gprim/geomfuncs.cpp
	libsrc/gprim/geomtest3d.cpp
	libsrc/general/hashtabl.cpp
	libsrc/meshing/improve2.cpp
	libsrc/meshing/improve3.cpp
	libsrc/meshing/localh.cpp
	libsrc/linalg/polynomial.cpp
	libsrc/geom2d/spline.cpp )

