SET( NGLIB_SRCS
	libsrc/meshing/adfront2.cpp
	libsrc/meshing/adfront3.cpp
	libsrc/gprim/adtree.cpp
	libsrc/csg/algprim.cpp
	libsrc/general/array.cpp
	libsrc/linalg/bfgs.cpp
	libsrc/meshing/bisect.cpp
	libsrc/general/bitarray.cpp
	libsrc/meshing/boundarylayer.cpp
	libsrc/csg/brick.cpp
	libsrc/csg/bspline2d.cpp
	libsrc/meshing/clusters.cpp
	libsrc/csg/csgeom.cpp
	libsrc/csg/csgparser.cpp
	libsrc/csg/curve2d.cpp
	libsrc/meshing/curvedelems.cpp
	libsrc/meshing/delaunay.cpp
	libsrc/linalg/densemat.cpp
	libsrc/general/dynamicmem.cpp
	libsrc/csg/edgeflw.cpp
	libsrc/csg/explicitcurve2d.cpp
	libsrc/csg/extrusion.cpp
	libsrc/general/flags.cpp
	libsrc/csg/gencyl.cpp
	libsrc/csg/genmesh.cpp
	libsrc/geom2d/genmesh2d.cpp
	libsrc/gprim/geom2d.cpp
	libsrc/geom2d/geom2dmesh.cpp
	libsrc/gprim/geom3d.cpp
	libsrc/gprim/geomfuncs.cpp
	libsrc/meshing/geomsearch.cpp
	libsrc/gprim/geomtest3d.cpp
	libsrc/meshing/global.cpp
	libsrc/general/hashtabl.cpp
	libsrc/meshing/hprefinement.cpp
	libsrc/csg/identify.cpp
	libsrc/meshing/improve2.cpp
	libsrc/meshing/improve2gen.cpp
	libsrc/meshing/improve3.cpp
	libsrc/linalg/linopt.cpp
	libsrc/linalg/linsearch.cpp
	libsrc/meshing/localh.cpp
	libsrc/csg/manifold.cpp
	libsrc/meshing/meshclass.cpp
	libsrc/meshing/meshfunc.cpp
	libsrc/meshing/meshfunc2d.cpp
	libsrc/meshing/meshing2.cpp
	libsrc/meshing/meshing3.cpp
	libsrc/stlgeom/meshstlsurface.cpp
	libsrc/csg/meshsurf.cpp
	libsrc/meshing/meshtool.cpp
	libsrc/meshing/meshtype.cpp
	libsrc/meshing/msghandler.cpp
	libsrc/general/mystring.cpp
	libsrc/meshing/netrule2.cpp
	libsrc/meshing/netrule3.cpp
	libsrc/general/ngexception.cpp
	libsrc/general/optmem.cpp
	libsrc/meshing/parallelmesh.cpp
	libsrc/meshing/paralleltop.cpp
	libsrc/meshing/parser2.cpp
	libsrc/meshing/parser3.cpp
	libsrc/general/parthreads.cpp
	libsrc/csg/polyhedra.cpp
	libsrc/linalg/polynomial.cpp
	libsrc/meshing/prism2rls.cpp
	libsrc/general/profiler.cpp
	libsrc/meshing/pyramid2rls.cpp
	libsrc/meshing/pyramidrls.cpp
	libsrc/meshing/quadrls.cpp
	libsrc/interface/read_fnf_mesh.cpp
	libsrc/interface/readtetmesh.cpp
	libsrc/interface/readuser.cpp
	libsrc/meshing/refine.cpp
	libsrc/csg/revolution.cpp
	libsrc/meshing/ruler2.cpp
	libsrc/meshing/ruler3.cpp
	libsrc/meshing/secondorder.cpp
	libsrc/general/seti.cpp
	libsrc/csg/singularref.cpp
	libsrc/meshing/smoothing2.5.cpp
	libsrc/meshing/smoothing2.cpp
	libsrc/meshing/smoothing3.cpp
	libsrc/csg/solid.cpp
	libsrc/general/sort.cpp
	libsrc/general/spbita2d.cpp
	libsrc/meshing/specials.cpp
	libsrc/csg/specpoin.cpp
	libsrc/geom2d/spline.cpp
	libsrc/csg/spline3d.cpp
	libsrc/geom2d/splinegeometry.cpp
	libsrc/stlgeom/stlgeom.cpp
	libsrc/stlgeom/stlgeomchart.cpp
	libsrc/stlgeom/stlgeommesh.cpp
	libsrc/stlgeom/stlline.cpp
	libsrc/stlgeom/stltool.cpp
	libsrc/stlgeom/stltopology.cpp
	libsrc/csg/surface.cpp
	libsrc/general/symbolta.cpp
	libsrc/general/table.cpp
	libsrc/meshing/tetrarls.cpp
	libsrc/meshing/topology.cpp
	libsrc/gprim/transform3d.cpp
	libsrc/csg/triapprox.cpp
	libsrc/meshing/triarls.cpp
	libsrc/meshing/validate.cpp
	libsrc/interface/writeabaqus.cpp
	libsrc/interface/writediffpack.cpp
	libsrc/interface/writedolfin.cpp
	libsrc/interface/writeelmer.cpp
	libsrc/interface/writefeap.cpp
	libsrc/interface/writefluent.cpp
	libsrc/interface/writegmsh.cpp
	libsrc/interface/writegmsh2.cpp
	libsrc/interface/writejcm.cpp
	libsrc/interface/writepermas.cpp
	libsrc/interface/writetecplot.cpp
	libsrc/interface/writetet.cpp
	libsrc/interface/writetochnog.cpp
	libsrc/interface/writeuser.cpp
	libsrc/interface/wuchemnitz.cpp
	libsrc/meshing/zrefine.cpp
	nglib/nglib.cpp )

