SET( MESHING_SRCS
	libsrc/meshing/adfront2.cpp
	libsrc/meshing/adfront3.cpp
	libsrc/meshing/bcfunctions.cpp
	libsrc/meshing/bisect.cpp
	libsrc/meshing/boundarylayer.cpp
	libsrc/meshing/clusters.cpp
	libsrc/meshing/curvedelems.cpp
	libsrc/meshing/delaunay.cpp
	libsrc/meshing/geomsearch.cpp
	libsrc/meshing/global.cpp
	libsrc/meshing/hprefinement.cpp
	libsrc/meshing/improve2.cpp
	libsrc/meshing/improve2gen.cpp
	libsrc/meshing/improve3.cpp
	libsrc/meshing/localh.cpp
	libsrc/meshing/meshclass.cpp
	libsrc/meshing/meshfunc.cpp
	libsrc/meshing/meshfunc2d.cpp
	libsrc/meshing/meshing2.cpp
	libsrc/meshing/meshing3.cpp
	libsrc/meshing/meshtool.cpp
	libsrc/meshing/meshtype.cpp
	libsrc/meshing/msghandler.cpp
	libsrc/meshing/netrule2.cpp
	libsrc/meshing/netrule3.cpp
	libsrc/meshing/parallelmesh.cpp
	libsrc/meshing/paralleltop.cpp
	libsrc/meshing/parser2.cpp
	libsrc/meshing/parser3.cpp
	libsrc/meshing/prism2rls.cpp
	libsrc/meshing/pyramid2rls.cpp
	libsrc/meshing/pyramidrls.cpp
	libsrc/meshing/quadrls.cpp
	libsrc/meshing/refine.cpp
	libsrc/meshing/ruler2.cpp
	libsrc/meshing/ruler3.cpp
	libsrc/meshing/secondorder.cpp
	libsrc/meshing/smoothing2.cpp
	libsrc/meshing/smoothing3.cpp
	libsrc/meshing/specials.cpp
	libsrc/meshing/tetrarls.cpp
	libsrc/meshing/topology.cpp
	libsrc/meshing/triarls.cpp
	libsrc/meshing/validate.cpp
	libsrc/meshing/zrefine.cpp )
